apiVersion: batch/v1
kind: Job
metadata:
  name: nextflow-job
spec:
  template:
    spec:
      containers:
      - name: nextflow
        image: nextflow/nextflow
        command: ["nextflow", "run", "main.nf"]
        volumeMounts:
        - name: data
          mountPath: /mnt/data
      restartPolicy: Never
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nextflow-pvc
  backoffLimit: 2
